"use node";
import { v } from "convex/values";
import { fetchInstallationAccessToken } from "../_shared/githubApp";
import { internal } from "./_generated/api";
import {
  internalAction,
  type ActionCtx,
} from "./_generated/server";
import { Octokit } from "octokit";

const createOctokit = (token: string): Octokit => {
  return new Octokit({
    auth: token,
    userAgent: "cmux-github-bot",
    request: {
      timeout: 10_000,
    },
  });
};

const parseRepoFullName = (
  repoFullName: string,
): { owner: string; repo: string } | null => {
  const [owner, repo] = repoFullName.split("/");
  if (!owner || !repo) {
    return null;
  }
  return { owner, repo };
};

export const addPrReaction = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    content: v.literal("eyes"),
  },
  handler: async (
    _ctx,
    { installationId, repoFullName, prNumber, content },
  ) => {
    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for installation",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      const repo = parseRepoFullName(repoFullName);
      if (!repo) {
        console.error("[github_pr_comments] Invalid repo full name", {
          repoFullName,
        });
        return {
          ok: false,
          error: "Invalid repository name",
        };
      }

      const octokit = createOctokit(accessToken);
      const { data } = await octokit.rest.reactions.createForIssue({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: prNumber,
        content,
      });

      console.log("[github_pr_comments] Successfully added reaction", {
        installationId,
        repoFullName,
        prNumber,
        reactionId: data.id,
      });

      return { ok: true, reactionId: data.id };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error adding reaction",
        {
          installationId,
          repoFullName,
          prNumber,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

export const postPreviewComment = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    screenshotSetId: v.id("previewScreenshotSets"),
    previewRunId: v.id("previewRuns"),
  },
  handler: async (ctx, args) => {
    const { installationId, repoFullName, prNumber, screenshotSetId } = args;

    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for preview comment",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      const repo = parseRepoFullName(repoFullName);
      if (!repo) {
        console.error("[github_pr_comments] Invalid repo full name", {
          repoFullName,
        });
        return { ok: false, error: "Invalid repository name" };
      }

      const octokit = createOctokit(accessToken);

      // Get screenshot set
      const screenshotSet = await ctx.runQuery(
        internal.previewScreenshots.getScreenshotSet,
        { screenshotSetId },
      );

      if (!screenshotSet) {
        console.error("[github_pr_comments] Screenshot set not found", {
          screenshotSetId,
        });
        return { ok: false, error: "Screenshot set not found" };
      }

      // Build comment body
      let commentBody = "## Preview Screenshots\n\n";

      if (screenshotSet.status === "completed" && screenshotSet.images.length > 0) {
        commentBody += `Successfully captured ${screenshotSet.images.length} screenshot(s) for commit \`${screenshotSet.commitSha.slice(0, 7)}\`:\n\n`;

        for (const image of screenshotSet.images) {
          // Get storage URL for the image
          const storageUrl = await ctx.storage.getUrl(image.storageId);
          if (storageUrl) {
            const fileName = image.fileName || "screenshot";
            commentBody += `### ${fileName}\n`;
            commentBody += `![${fileName}](${storageUrl})\n\n`;
          }
        }

        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev)`;
      } else if (screenshotSet.status === "failed") {
        commentBody += `Failed to capture screenshots: ${screenshotSet.error || "Unknown error"}\n\n`;
        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev)`;
      } else if (screenshotSet.status === "skipped") {
        commentBody += `Screenshot capture was skipped: ${screenshotSet.error || "No preview configured"}\n\n`;
        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev)`;
      }

      // Post comment to GitHub
      const { data } = await octokit.rest.issues.createComment({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: prNumber,
        body: commentBody,
      });

      console.log("[github_pr_comments] Successfully posted preview comment", {
        installationId,
        repoFullName,
        prNumber,
        commentId: data.id,
        commentUrl: data.html_url,
      });

      // Update preview run with comment URL
      if (data.html_url) {
        await ctx.runMutation(internal.previewRuns.updateStatus, {
          previewRunId: args.previewRunId,
          status: "completed",
          screenshotSetId,
          githubCommentUrl: data.html_url,
        });
      }

      return { ok: true, commentId: data.id, commentUrl: data.html_url };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error posting preview comment",
        {
          installationId,
          repoFullName,
          prNumber,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

export const addPrComment = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    body: v.string(),
  },
  handler: async (
    _ctx,
    { installationId, repoFullName, prNumber, body },
  ) => {
    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for installation",
          { installationId },
        );
        return { ok: false as const, error: "Failed to get access token" };
      }

      const repo = parseRepoFullName(repoFullName);
      if (!repo) {
        console.error("[github_pr_comments] Invalid repo full name", {
          repoFullName,
        });
        return { ok: false as const, error: "Invalid repository name" };
      }

      const octokit = createOctokit(accessToken);
      const { data } = await octokit.rest.issues.createComment({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: prNumber,
        body,
      });
      console.log("[github_pr_comments] Successfully added comment", {
        installationId,
        repoFullName,
        prNumber,
        commentId: data.id,
      });

      return { ok: true as const, commentId: data.id };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error adding comment",
        {
          installationId,
          repoFullName,
          prNumber,
          error,
        },
      );
      return {
        ok: false as const,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

async function getScreenshotsForPr(
  ctx: ActionCtx,
  {
    teamId,
    repoFullName,
    prNumber,
  }: {
    teamId: string;
    repoFullName: string;
    prNumber: number;
  },
): Promise<Array<{ url: string; fileName?: string }>> {
  try {
    // Find task runs that have this PR
    const taskRuns = await ctx.runQuery(
      internal.github_pr_queries.findTaskRunsForPr,
      {
        teamId,
        repoFullName,
        prNumber,
      },
    );

    if (taskRuns.length === 0) {
      return [];
    }

    // Get screenshots from the latest task run
    const screenshots: Array<{ url: string; fileName?: string }> = [];

    for (const run of taskRuns) {
      if (run.latestScreenshotSetId) {
        const screenshotSet = await ctx.runQuery(
          internal.github_pr_queries.getScreenshotSet,
          {
            screenshotSetId: run.latestScreenshotSetId,
          },
        );

        if (screenshotSet && screenshotSet.status === "completed") {
          for (const image of screenshotSet.images) {
            if (image.url) {
              screenshots.push({
                url: image.url,
                fileName: image.fileName,
              });
            }
          }
        }
      }
    }

    return screenshots;
  } catch (error) {
    console.error(
      "[github_pr_comments] Error fetching screenshots for PR",
      {
        teamId,
        repoFullName,
        prNumber,
        error,
      },
    );
    return [];
  }
}

function formatScreenshotComment(
  screenshots: Array<{ url: string; fileName?: string }>,
): string {
  if (screenshots.length === 0) {
    return "";
  }

  let markdown = "## Screenshots\n\n";
  markdown +=
    "Here are the screenshots from the latest run:\n\n";

  for (const screenshot of screenshots) {
    const title = screenshot.fileName || "Screenshot";
    markdown += `### ${title}\n\n`;
    markdown += `![${title}](${screenshot.url})\n\n`;
  }

  return markdown;
}

export const postPreviewCommentWithTaskScreenshots = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    taskRunId: v.id("taskRuns"),
    previewRunId: v.id("previewRuns"),
  },
  handler: async (ctx, args) => {
    const { installationId, repoFullName, prNumber, taskRunId, previewRunId } = args;

    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for preview comment",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      const repo = parseRepoFullName(repoFullName);
      if (!repo) {
        console.error("[github_pr_comments] Invalid repo full name", {
          repoFullName,
        });
        return { ok: false, error: "Invalid repository name" };
      }

      const octokit = createOctokit(accessToken);

      // Get task run to find screenshot set
      const taskRun = await ctx.runQuery(internal.taskRuns.getById, {
        id: taskRunId,
      });

      if (!taskRun?.latestScreenshotSetId) {
        console.error("[github_pr_comments] No screenshot set for task run", {
          taskRunId,
        });
        return { ok: false, error: "No screenshot set found" };
      }

      // Get screenshot set from task run
      const screenshotSet = await ctx.runQuery(
        internal.github_pr_queries.getScreenshotSet,
        { screenshotSetId: taskRun.latestScreenshotSetId },
      );

      if (!screenshotSet) {
        console.error("[github_pr_comments] Screenshot set not found", {
          screenshotSetId: taskRun.latestScreenshotSetId,
        });
        return { ok: false, error: "Screenshot set not found" };
      }

      // Build comment body
      let commentBody = "## Preview Screenshots\n\n";

      if (screenshotSet.status === "completed" && screenshotSet.images.length > 0) {
        commentBody += `Successfully captured ${screenshotSet.images.length} screenshot(s) for commit \`${(screenshotSet.commitSha || "").slice(0, 7)}\`:\n\n`;

        for (const image of screenshotSet.images) {
          // Get storage URL for the image
          const storageUrl = await ctx.storage.getUrl(image.storageId);
          if (storageUrl) {
            const fileName = image.fileName || "screenshot";
            commentBody += `### ${fileName}\n`;
            commentBody += `![${fileName}](${storageUrl})\n\n`;
          }
        }

        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev) preview system_`;
      } else if (screenshotSet.status === "failed") {
        commentBody += `Failed to capture screenshots: ${screenshotSet.error || "Unknown error"}\n\n`;
        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev) preview system_`;
      } else if (screenshotSet.status === "skipped") {
        commentBody += `Screenshot capture was skipped: ${screenshotSet.error || "No preview configured"}\n\n`;
        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev) preview system_`;
      }

      // Post comment to GitHub
      const { data } = await octokit.rest.issues.createComment({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: prNumber,
        body: commentBody,
      });
      console.log("[github_pr_comments] Successfully posted preview comment", {
        installationId,
        repoFullName,
        prNumber,
        commentId: data.id,
        commentUrl: data.html_url,
      });

      // Update preview run with comment URL
      if (data.html_url) {
        await ctx.runMutation(internal.previewRuns.updateStatus, {
          previewRunId,
          status: "completed",
          githubCommentUrl: data.html_url,
        });
      }

      return { ok: true, commentId: data.id, commentUrl: data.html_url };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error posting preview comment",
        {
          installationId,
          repoFullName,
          prNumber,
          taskRunId,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

export const addScreenshotCommentToPr = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    teamId: v.string(),
  },
  handler: async (
    ctx,
    { installationId, repoFullName, prNumber, teamId },
  ): Promise<
    | { ok: true; commentId?: number; skipped?: boolean; reason?: string }
    | { ok: false; error: string }
  > => {
    try {
      const screenshots = await getScreenshotsForPr(ctx, {
        teamId,
        repoFullName,
        prNumber,
      });

      if (screenshots.length === 0) {
        console.log(
          "[github_pr_comments] No screenshots found for PR",
          {
            installationId,
            repoFullName,
            prNumber,
          },
        );
        return { ok: true as const, skipped: true, reason: "No screenshots found" };
      }

      const body = formatScreenshotComment(screenshots);

      const result = await ctx.runAction(internal.github_pr_comments.addPrComment, {
        installationId,
        repoFullName,
        prNumber,
        body,
      });

      if (result.ok) {
        return { ok: true as const, commentId: result.commentId };
      }

      return { ok: false as const, error: result.error };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error adding screenshot comment",
        {
          installationId,
          repoFullName,
          prNumber,
          teamId,
          error,
        },
      );
      return {
        ok: false as const,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});
